-- MySQL Script generated by MySQL Workbench
-- Mon Sep 12 11:29:56 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`PessoasFísicas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PessoasFísicas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PessoasFísicas` (
  `idPessoaFísica` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `cpf` VARCHAR(45) NULL,
  `endereço` VARCHAR(45) NULL,
  PRIMARY KEY (`idPessoaFísica`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`PessoasJurídicas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PessoasJurídicas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PessoasJurídicas` (
  `idPessoaJurídica` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `cnpj` VARCHAR(45) NULL,
  `endereço` VARCHAR(45) NULL,
  PRIMARY KEY (`idPessoaJurídica`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Clientes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Clientes` (
  `idCliente` INT NOT NULL,
  `identificação` VARCHAR(45) NULL,
  `PessoasFísicas_idPessoaFísica` INT NOT NULL,
  `PessoasJurídicas_idPessoaJurídica` INT NOT NULL,
  PRIMARY KEY (`idCliente`, `PessoasFísicas_idPessoaFísica`, `PessoasJurídicas_idPessoaJurídica`),
  INDEX `fk_Clientes_PessoasFísicas1_idx` (`PessoasFísicas_idPessoaFísica` ASC) VISIBLE,
  INDEX `fk_Clientes_PessoasJurídicas1_idx` (`PessoasJurídicas_idPessoaJurídica` ASC) VISIBLE,
  CONSTRAINT `fk_Clientes_PessoasFísicas1`
    FOREIGN KEY (`PessoasFísicas_idPessoaFísica`)
    REFERENCES `mydb`.`PessoasFísicas` (`idPessoaFísica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Clientes_PessoasJurídicas1`
    FOREIGN KEY (`PessoasJurídicas_idPessoaJurídica`)
    REFERENCES `mydb`.`PessoasJurídicas` (`idPessoaJurídica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pedidos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pedidos` (
  `idPedidos` INT NOT NULL,
  `statusDoPedido` VARCHAR(45) NULL,
  `descrição` VARCHAR(45) NULL,
  `Clientes_idCliente` INT NOT NULL,
  `frete` FLOAT NULL,
  PRIMARY KEY (`idPedidos`, `Clientes_idCliente`),
  INDEX `fk_Pedidos_Clientes1_idx` (`Clientes_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Pedidos_Clientes1`
    FOREIGN KEY (`Clientes_idCliente`)
    REFERENCES `mydb`.`Clientes` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Produtos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Produtos` (
  `idProduto` INT NOT NULL,
  `categoria` VARCHAR(45) NULL,
  `descrição` VARCHAR(45) NULL,
  `valor` VARCHAR(45) NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Fornecedores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Fornecedores` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Fornecedores` (
  `idFornecedor` INT NOT NULL,
  `razaoSocial` VARCHAR(45) NULL,
  `cnpj` VARCHAR(45) NULL,
  PRIMARY KEY (`idFornecedor`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`DisponibilidadesDeProdutos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DisponibilidadesDeProdutos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DisponibilidadesDeProdutos` (
  `Fornecedores_idFornecedor` INT NOT NULL,
  `Produtos_idProduto` INT NOT NULL,
  PRIMARY KEY (`Fornecedores_idFornecedor`, `Produtos_idProduto`),
  INDEX `fk_Fornecedores_has_Produtos_Produtos1_idx` (`Produtos_idProduto` ASC) VISIBLE,
  INDEX `fk_Fornecedores_has_Produtos_Fornecedor_idx` (`Fornecedores_idFornecedor` ASC) VISIBLE,
  CONSTRAINT `fk_Fornecedores_has_Produtos_Fornecedor`
    FOREIGN KEY (`Fornecedores_idFornecedor`)
    REFERENCES `mydb`.`Fornecedores` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fornecedores_has_Produtos_Produtos1`
    FOREIGN KEY (`Produtos_idProduto`)
    REFERENCES `mydb`.`Produtos` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Estoques`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Estoques` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Estoques` (
  `idEstoque` INT NOT NULL,
  `Local` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstoque`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Produtos/Estoques`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Produtos/Estoques` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Produtos/Estoques` (
  `Produtos_idProduto` INT NOT NULL,
  `Estoques_idEstoque` INT NOT NULL,
  `quantidade` INT NULL,
  PRIMARY KEY (`Produtos_idProduto`, `Estoques_idEstoque`),
  INDEX `fk_Produtos_has_Estoques_Estoques1_idx` (`Estoques_idEstoque` ASC) VISIBLE,
  INDEX `fk_Produtos_has_Estoques_Produtos1_idx` (`Produtos_idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_Produtos_has_Estoques_Produtos1`
    FOREIGN KEY (`Produtos_idProduto`)
    REFERENCES `mydb`.`Produtos` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produtos_has_Estoques_Estoques1`
    FOREIGN KEY (`Estoques_idEstoque`)
    REFERENCES `mydb`.`Estoques` (`idEstoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Relações de Produtos/Pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Relações de Produtos/Pedidos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Relações de Produtos/Pedidos` (
  `Pedidos_idPedidos` INT NOT NULL,
  `Produtos_idProduto` INT NOT NULL,
  `quantidade` VARCHAR(45) NULL,
  PRIMARY KEY (`Pedidos_idPedidos`, `Produtos_idProduto`),
  INDEX `fk_Pedidos_has_Produtos_Produtos1_idx` (`Produtos_idProduto` ASC) VISIBLE,
  INDEX `fk_Pedidos_has_Produtos_Pedidos1_idx` (`Pedidos_idPedidos` ASC) VISIBLE,
  CONSTRAINT `fk_Pedidos_has_Produtos_Pedidos1`
    FOREIGN KEY (`Pedidos_idPedidos`)
    REFERENCES `mydb`.`Pedidos` (`idPedidos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedidos_has_Produtos_Produtos1`
    FOREIGN KEY (`Produtos_idProduto`)
    REFERENCES `mydb`.`Produtos` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Terceirizados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Terceirizados` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Terceirizados` (
  `idTerceirizado` INT NOT NULL,
  `razãoSocial` VARCHAR(45) NULL,
  `endereço` VARCHAR(45) NULL,
  PRIMARY KEY (`idTerceirizado`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Produtos por Terceirizados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Produtos por Terceirizados` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Produtos por Terceirizados` (
  `Terceirizados_idTerceirizado` INT NOT NULL,
  `Produtos_idProduto` INT NOT NULL,
  `quantidade` INT NULL,
  PRIMARY KEY (`Terceirizados_idTerceirizado`, `Produtos_idProduto`),
  INDEX `fk_Terceirizados_has_Produtos_Produtos1_idx` (`Produtos_idProduto` ASC) VISIBLE,
  INDEX `fk_Terceirizados_has_Produtos_Terceirizados1_idx` (`Terceirizados_idTerceirizado` ASC) VISIBLE,
  CONSTRAINT `fk_Terceirizados_has_Produtos_Terceirizados1`
    FOREIGN KEY (`Terceirizados_idTerceirizado`)
    REFERENCES `mydb`.`Terceirizados` (`idTerceirizado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Terceirizados_has_Produtos_Produtos1`
    FOREIGN KEY (`Produtos_idProduto`)
    REFERENCES `mydb`.`Produtos` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Pagamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pagamentos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pagamentos` (
  `idPagamento` INT NOT NULL,
  `formaDePagamento` INT NULL,
  `Pedidos_idPedidos` INT NOT NULL,
  `Pedidos_Clientes_idCliente` INT NOT NULL,
  PRIMARY KEY (`idPagamento`, `Pedidos_idPedidos`, `Pedidos_Clientes_idCliente`),
  INDEX `fk_Pagamentos_Pedidos1_idx` (`Pedidos_idPedidos` ASC, `Pedidos_Clientes_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Pagamentos_Pedidos1`
    FOREIGN KEY (`Pedidos_idPedidos` , `Pedidos_Clientes_idCliente`)
    REFERENCES `mydb`.`Pedidos` (`idPedidos` , `Clientes_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Entregas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Entregas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Entregas` (
  `idEntrega` INT NOT NULL,
  `descrição` VARCHAR(45) NULL,
  `dataDoPedido` DATE NULL,
  `dataDoEnvio` DATE NULL,
  `dataDaEntrega` DATE NULL,
  `códigoDeRastreio` VARCHAR(45) NULL,
  `Pedidos_idPedidos` INT NOT NULL,
  `Pedidos_Clientes_idCliente` INT NOT NULL,
  PRIMARY KEY (`idEntrega`, `Pedidos_idPedidos`, `Pedidos_Clientes_idCliente`),
  INDEX `fk_Entregas_Pedidos1_idx` (`Pedidos_idPedidos` ASC, `Pedidos_Clientes_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Entregas_Pedidos1`
    FOREIGN KEY (`Pedidos_idPedidos` , `Pedidos_Clientes_idCliente`)
    REFERENCES `mydb`.`Pedidos` (`idPedidos` , `Clientes_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`PIX`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PIX` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PIX` (
  `idPIX` INT NOT NULL,
  `valor` FLOAT NULL,
  `dataDoPagamento` DATE NULL,
  `Pagamentos_idPagamento` INT NOT NULL,
  `Pagamentos_Pedidos_idPedidos` INT NOT NULL,
  `Pagamentos_Pedidos_Clientes_idCliente` INT NOT NULL,
  PRIMARY KEY (`idPIX`, `Pagamentos_idPagamento`, `Pagamentos_Pedidos_idPedidos`, `Pagamentos_Pedidos_Clientes_idCliente`),
  INDEX `fk_PIX_Pagamentos1_idx` (`Pagamentos_idPagamento` ASC, `Pagamentos_Pedidos_idPedidos` ASC, `Pagamentos_Pedidos_Clientes_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_PIX_Pagamentos1`
    FOREIGN KEY (`Pagamentos_idPagamento` , `Pagamentos_Pedidos_idPedidos` , `Pagamentos_Pedidos_Clientes_idCliente`)
    REFERENCES `mydb`.`Pagamentos` (`idPagamento` , `Pedidos_idPedidos` , `Pedidos_Clientes_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Boletos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Boletos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Boletos` (
  `idBoleto` INT NOT NULL,
  `valor` FLOAT NULL,
  `dataDoPagamento` DATE NULL,
  `Pagamentos_idPagamento` INT NOT NULL,
  `Pagamentos_Pedidos_idPedidos` INT NOT NULL,
  `Pagamentos_Pedidos_Clientes_idCliente` INT NOT NULL,
  PRIMARY KEY (`idBoleto`, `Pagamentos_idPagamento`, `Pagamentos_Pedidos_idPedidos`, `Pagamentos_Pedidos_Clientes_idCliente`),
  INDEX `fk_Boleto_Pagamentos1_idx` (`Pagamentos_idPagamento` ASC, `Pagamentos_Pedidos_idPedidos` ASC, `Pagamentos_Pedidos_Clientes_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Boleto_Pagamentos1`
    FOREIGN KEY (`Pagamentos_idPagamento` , `Pagamentos_Pedidos_idPedidos` , `Pagamentos_Pedidos_Clientes_idCliente`)
    REFERENCES `mydb`.`Pagamentos` (`idPagamento` , `Pedidos_idPedidos` , `Pedidos_Clientes_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Cartões`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cartões` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cartões` (
  `idCartão` INT NOT NULL,
  `tipoDoCartão` VARCHAR(45) NULL,
  `dataDoPagamento` DATE NULL,
  `númeroDoCartão` INT NULL,
  `valor` FLOAT NULL,
  `Pagamentos_idPagamento` INT NOT NULL,
  `Pagamentos_Pedidos_idPedidos` INT NOT NULL,
  `Pagamentos_Pedidos_Clientes_idCliente` INT NOT NULL,
  PRIMARY KEY (`idCartão`, `Pagamentos_idPagamento`, `Pagamentos_Pedidos_idPedidos`, `Pagamentos_Pedidos_Clientes_idCliente`),
  INDEX `fk_Cartões_Pagamentos1_idx` (`Pagamentos_idPagamento` ASC, `Pagamentos_Pedidos_idPedidos` ASC, `Pagamentos_Pedidos_Clientes_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Cartões_Pagamentos1`
    FOREIGN KEY (`Pagamentos_idPagamento` , `Pagamentos_Pedidos_idPedidos` , `Pagamentos_Pedidos_Clientes_idCliente`)
    REFERENCES `mydb`.`Pagamentos` (`idPagamento` , `Pedidos_idPedidos` , `Pedidos_Clientes_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;