-- MySQL Script generated by MySQL Workbench
-- Mon Sep 12 17:04:33 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Oficina
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Oficina
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Oficina` DEFAULT CHARACTER SET utf8 ;
USE `Oficina` ;

-- -----------------------------------------------------
-- Table `Oficina`.`Clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Oficina`.`Clientes` ;

CREATE TABLE IF NOT EXISTS `Oficina`.`Clientes` (
  `idCliente` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `placa` VARCHAR(45) NOT NULL,
  `modeloEAno` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Oficina`.`Mecânicos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Oficina`.`Mecânicos` ;

CREATE TABLE IF NOT EXISTS `Oficina`.`Mecânicos` (
  `idMecanico` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `setor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMecanico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Oficina`.`Ordens de Serviço`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Oficina`.`Ordens de Serviço` ;

CREATE TABLE IF NOT EXISTS `Oficina`.`Ordens de Serviço` (
  `idServiço` INT NOT NULL,
  `serviçoConcluído` TINYINT NOT NULL,
  `valorDoServiço` DOUBLE NOT NULL,
  `valorDasPeças` DOUBLE NOT NULL,
  `valorTotal` DOUBLE NOT NULL,
  `pago` TINYINT NOT NULL,
  PRIMARY KEY (`idServiço`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Oficina`.`Revisões de Orçamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Oficina`.`Revisões de Orçamento` ;

CREATE TABLE IF NOT EXISTS `Oficina`.`Revisões de Orçamento` (
  `idRevisãoDeOrçamento` INT NOT NULL,
  `serviço` VARCHAR(45) NOT NULL,
  `valorDoServiço` INT NOT NULL,
  `peças` VARCHAR(45) NOT NULL,
  `valorDasPeças` INT NOT NULL,
  `descrição` VARCHAR(45) NOT NULL,
  `Mecânicos_idMecanico` INT NOT NULL,
  `Serviços_idServiço` INT NOT NULL,
  PRIMARY KEY (`idRevisãoDeOrçamento`, `Mecânicos_idMecanico`, `Serviços_idServiço`),
  INDEX `fk_Revisão-orçamento_mecanico1_idx` (`Mecânicos_idMecanico` ASC) VISIBLE,
  INDEX `fk_Revisão-orçamento_sertviço1_idx` (`Serviços_idServiço` ASC) VISIBLE,
  CONSTRAINT `fk_Revisão-orçamento_mecanico1`
    FOREIGN KEY (`Mecânicos_idMecanico`)
    REFERENCES `Oficina`.`Mecânicos` (`idMecanico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Revisão-orçamento_sertviço1`
    FOREIGN KEY (`Serviços_idServiço`)
    REFERENCES `Oficina`.`Ordens de Serviço` (`idServiço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Oficina`.`Entradas de Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Oficina`.`Entradas de Cliente` ;

CREATE TABLE IF NOT EXISTS `Oficina`.`Entradas de Cliente` (
  `Clientes_idCliente` INT NOT NULL,
  `Revisões de Orçamento_idRevisãoDeOrçamento` INT NOT NULL,
  `data` DATE NOT NULL,
  PRIMARY KEY (`Clientes_idCliente`, `Revisões de Orçamento_idRevisãoDeOrçamento`),
  INDEX `fk_Cliente_has_Revisão-orçamento_Revisão-orçamento1_idx` (`Revisões de Orçamento_idRevisãoDeOrçamento` ASC) VISIBLE,
  INDEX `fk_Cliente_has_Revisão-orçamento_Cliente_idx` (`Clientes_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_has_Revisão-orçamento_Cliente`
    FOREIGN KEY (`Clientes_idCliente`)
    REFERENCES `Oficina`.`Clientes` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_has_Revisão-orçamento_Revisão-orçamento1`
    FOREIGN KEY (`Revisões de Orçamento_idRevisãoDeOrçamento`)
    REFERENCES `Oficina`.`Revisões de Orçamento` (`idRevisãoDeOrçamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Oficina`.`Peças da Loja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Oficina`.`Peças da Loja` ;

CREATE TABLE IF NOT EXISTS `Oficina`.`Peças da Loja` (
  `idPeças` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `quantidade` INT NOT NULL,
  `valor` INT NOT NULL,
  PRIMARY KEY (`idPeças`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Oficina`.`peças_externas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Oficina`.`peças_externas` ;

CREATE TABLE IF NOT EXISTS `Oficina`.`peças_externas` (
  `idPeçasExternas` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `preço` VARCHAR(45) NOT NULL,
  `nomeDaLoja` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPeçasExternas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Oficina`.`instalação de peças`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Oficina`.`instalação de peças` ;

CREATE TABLE IF NOT EXISTS `Oficina`.`instalação de peças` (
  `Peças_idPeças` INT NOT NULL,
  `Revisões de Orçamento_idRevisãoDeOrçamento` INT NOT NULL,
  `Revisões de Orçamento_Mecânicos_idMecânico` INT NOT NULL,
  `Revisões de Orçamento_Serviços_idServiço` INT NOT NULL,
  `Peças Externas_idPeçaExterna` INT NOT NULL,
  PRIMARY KEY (`Peças_idPeças`, `Revisões de Orçamento_idRevisãoDeOrçamento`, `Revisões de Orçamento_Mecânicos_idMecânico`, `Revisões de Orçamento_Serviços_idServiço`, `Peças Externas_idPeçaExterna`),
  INDEX `fk_peças_has_Revisão-orçamento_Revisão-orçamento1_idx` (`Revisões de Orçamento_idRevisãoDeOrçamento` ASC, `Revisões de Orçamento_Mecânicos_idMecânico` ASC, `Revisões de Orçamento_Serviços_idServiço` ASC) VISIBLE,
  INDEX `fk_peças_has_Revisão-orçamento_peças1_idx` (`Peças_idPeças` ASC) VISIBLE,
  INDEX `fk_instalação de peças_peças_externas1_idx` (`Peças Externas_idPeçaExterna` ASC) VISIBLE,
  CONSTRAINT `fk_peças_has_Revisão-orçamento_peças1`
    FOREIGN KEY (`Peças_idPeças`)
    REFERENCES `Oficina`.`Peças da Loja` (`idPeças`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_peças_has_Revisão-orçamento_Revisão-orçamento1`
    FOREIGN KEY (`Revisões de Orçamento_idRevisãoDeOrçamento` , `Revisões de Orçamento_Mecânicos_idMecânico` , `Revisões de Orçamento_Serviços_idServiço`)
    REFERENCES `Oficina`.`Revisões de Orçamento` (`idRevisãoDeOrçamento` , `Mecânicos_idMecanico` , `Serviços_idServiço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_instalação de peças_peças_externas1`
    FOREIGN KEY (`Peças Externas_idPeçaExterna`)
    REFERENCES `Oficina`.`peças_externas` (`idPeçasExternas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
